### PR TITLE
fix(grammar): bump javascript version and regenerate

### PR DESCRIPTION
**Pull request by clason**
Adapt to breaking upstream regex change (via tree-sitter-javascript dependency). Also regenerate bindings with latest tree-sitter CLI.

### CODE REVIEW

**Comment by yuja** [comment]
Updated dependencies by 2c02a5b1. Please let me know if there are still missing parts. Thanks.

**Comment by clason** [comment]
Yes, seems to work now. Thanks.

**Comment by clason** [comment]
(But you forgot to add the new headers.)

**Comment by clason** [comment]
On a related note, if you don't actually implement a scanner, you can -- and should -- just remove that file.

**Comment by yuja** [comment]
> (But you forgot to add the new headers.)

Is there a new header in addition to `tree-sitter-typescript/common/scanner.h`?
Do you mean `<tree_sitter/parser.h>` should be changed to `"tree_sitter/parser.h"`?

> if you don't actually implement a scanner, you can -- and should -- just remove that file.

I want to remove it, but I don't know how to enable ts scanner without adding `scanner.c` stub.

**Comment by clason** [comment]
> Is there a new header in addition to `tree-sitter-typescript/common/scanner.h`? Do you mean 

Yes, `array.h` and `alloc.h`

> `<tree_sitter/parser.h>` should be changed to `"tree_sitter/parser.h"`?

Yes.

See _my_ PR.

> I want to remove it, but I don't know how to enable ts scanner without adding `scanner.c` stub.

Ah, ok, I didn't realize that. Never mind then.

**Comment by yuja** [comment]
> > Is there a new header in addition to `tree-sitter-typescript/common/scanner.h`? Do you mean
> 
> Yes, `array.h` and `alloc.h`

Ok, they'll probably be added if tree-sitter-cli is upgraded to 0.22.x.

> > `<tree_sitter/parser.h>` should be changed to `"tree_sitter/parser.h"`?
> 
> Yes.

Fixed, thanks.

**Comment by clason** [comment]
> Ok, they'll probably be added if tree-sitter-cli is upgraded to 0.22.x.

Yes, that is correct. (They added a bunch more bindings, too, but I didn't want to spam the PR. Try `tree-sitter generate` locally and see what you like.)

**Comment by yuja** [comment]
I try to stick to what tree-sitter-typescript does because QML grammar is a monkey-patched ts grammar.

**Comment by clason** [comment]
Which is a bit behind, granted, but will automate updates soon.

**Pull request closed without merging**
